import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import Providers from "@/components/provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './../globals.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function DashboardLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <Providers>
            <html>
                <body className={inter.className}>
                    <Navbar />
                    {children}
                    <Footer />
                </body>
            </html>
        </Providers>
    );
}
